# Generated by Django 5.1.6 on 2025-02-19 10:04

import django.db.models.deletion
import django.utils.timezone
import leagues.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome lega')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('join_code', models.CharField(default=leagues.models.generate_league_code, max_length=6, unique=True, verbose_name='Codice di accesso')),
                ('president', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presided_leagues', to=settings.AUTH_USER_MODEL, verbose_name='Presidente')),
            ],
            options={
                'verbose_name': 'Lega',
                'verbose_name_plural': 'Leghe',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data partita')),
                ('team1_sets', models.PositiveSmallIntegerField(default=0, verbose_name='Set Squadra 1')),
                ('team2_sets', models.PositiveSmallIntegerField(default=0, verbose_name='Set Squadra 2')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='leagues.league', verbose_name='Lega')),
            ],
            options={
                'verbose_name': 'Partita',
                'verbose_name_plural': 'Partite',
                'ordering': ['-match_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.league')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Iscrizione',
                'verbose_name_plural': 'Iscrizioni',
                'unique_together': {('player', 'league')},
            },
        ),
        migrations.AddField(
            model_name='league',
            name='players',
            field=models.ManyToManyField(related_name='leagues', through='leagues.Membership', to=settings.AUTH_USER_MODEL, verbose_name='Giocatori'),
        ),
        migrations.CreateModel(
            name='MatchPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.PositiveSmallIntegerField(choices=[(1, 'Squadra 1'), (2, 'Squadra 2')])),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='leagues.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Giocatore partita',
                'verbose_name_plural': 'Giocatori partita',
                'unique_together': {('match', 'player')},
            },
        ),
    ]
